services:
  powersync:
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy
    restart: unless-stopped
    image: docker.io/journeyapps/powersync-service:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    command: ["start", "-r", "unified"]
    volumes:
      - ./config-powersync:/config:ro
    env_file:
      - ../config/prod.env
    environment:
      POWERSYNC_CONFIG_PATH: /config/powersync.yaml
      PS_JWKS_URL: http://web:8000/api/v2/powersync-keys
    expose:
      - 8080
      - 9090
